### PR TITLE
Update rustc-ap-* -> 148.0.0

### LINKED ISSUE #2738: Test test::verify_check_works failing on windows
This windows bug happens no matter the git `autocrlf` configuration.
Here is the result:
```shell
---- test::verify_check_works stdout ----
thread 'test::verify_check_works' panicked at 'Assertion failed for `{XXX}\rustfmt\target\debug\rustfmt --check .\temp_check.rs`
with: Unexpected return status: failure
stdout=``````
stderr=```Unrecognized option: 'check'
```', {XXX}\.cargo\registry\src\github.com-1ecc6299db9ec823\assert_cli-0.6.1\src\assert.rs:441:13
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```
Where `{XXX}` is my home folder.

After a git bisect, the responsible commit is 5d9f5aa05a668e7dfef87b46d89dad2884df9d41

### LINKED ISSUE #2743: Format obsolete `<-` expressions
I think these should format just like binops.

### LINKED ISSUE #2744: build failure with latest nightly
rustc 1.28.0-nightly (990d8aa74 2018-05-25)
I was trying to build rustfmt-nightly v0.8.2

````
   Compiling rustc-ap-rustc_data_structures v147.0.0
error[E0599]: no method named `start_bound` found for type `R` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-147.0.0/array_vec.rs:122:33
    |
122 |         let start = match range.start_bound() {
    |                                 ^^^^^^^^^^^
error[E0599]: no method named `end_bound` found for type `R` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-147.0.0/array_vec.rs:127:31
    |
127 |         let end = match range.end_bound() {
    |                               ^^^^^^^^^
error[E0599]: no method named `start_bound` found for type `R` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-147.0.0/sorted_map.rs:218:33
    |
218 |         let start = match range.start_bound() {
    |                                 ^^^^^^^^^^^
error[E0599]: no method named `end_bound` found for type `R` in the current scope
   --> /home/matthias/.cargo/registry/src/github.com-1ecc6299db9ec823/rustc-ap-rustc_data_structures-147.0.0/sorted_map.rs:233:31
    |
233 |         let end = match range.end_bound() {
    |                               ^^^^^^^^^
error: aborting due to 4 previous errors
````

Perhaps bumping the dependency version of the package fixes the problem?

### PR DESCRIPTION
**Pull request by alexheretic**
* Fixes latest nightly compile, resolves #2744
* Resolves #2743 as match arm is itself obsolete
* Add a more merciful test failure message for devs that run `cargo test` on this project before `cargo build`, resolves #2738

### CODE REVIEW

**Comment by topecongiro** [comment]
Thank you!
