### ISSUE TITLE
Fails to build with rustc 1.23.0-nightly (d762b1d6c 2017-11-04)

### ISSUE THREAD

**Issue by kraai** [rust-lang-nursery/rustfmt#2119]
When I try to build rustfmt with rustc 1.23.0-nightly (d762b1d6c 2017-11-04), it fails with the following errors:

```
$ cargo build
   Compiling rustfmt-nightly v0.2.13 (file:///home/kraai/src/rustfmt)
error[E0599]: no associated item named `DefaultImpl` found for type `syntax::ast::ItemKind` in the current scope
   --> src/visitor.rs:421:13
    |
421 |             ast::ItemKind::DefaultImpl(..) => {
    |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error[E0023]: this pattern has 4 fields, but the corresponding tuple variant has 5 fields
   --> src/items.rs:897:12
    |
897 |     if let ast::ItemKind::Trait(unsafety, ref generics, ref type_param_bounds, ref trait_items) =
    |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected 5 fields, found 4

error: aborting due to 2 previous errors

error: Could not compile `rustfmt-nightly`.

To learn more, run the command again with --verbose.
```

**Comment by topecongiro** [comment]
@kraai Thank you! Closed by #2118.
