### ISSUE TITLE
Does not compile on 1.23.0-nightly (269cf5026 2017-10-28)

### ISSUE THREAD

**Issue by dtolnay** [rust-lang-nursery/rustfmt#2096]
https://github.com/rust-lang-nursery/rustfmt/blob/485ef93e4912f80aed68867f7dfc163f5662d3a4/src/items.rs#L2714

```
error[E0004]: non-exhaustive patterns: `Ty` not covered
    --> .cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.2.12/src/items.rs:2714:30
     |
2714 |         let item_str = match self.node {
     |                              ^^^^^^^^^ pattern `Ty` not covered
```

The new variant is from https://github.com/rust-lang/rust/pull/44295 which merged yesterday.
