### ISSUE TITLE
rustfmt-nightly not building on latest nightly

### ISSUE THREAD

**Issue by vignesh-sankaran** [rust-lang-nursery/rustfmt#2307]
On the nightly version `rustc 1.24.0-nightly (5165ee9e2 2017-12-22)`, I get the following error while building rustfmt:
```
error[E0063]: missing field `recovered` in initializer of `syntax::ast::Block`
   --> /Users/vignesh/.cargo/registry/src/github.com-1ecc6299db9ec823/rustfmt-nightly-0.3.3/src/closures.rs:127:17
    |
127 |     let block = ast::Block {
    |                 ^^^^^^^^^^ missing `recovered`
```

**Comment by topecongiro** [comment]
Caused by https://github.com/rust-lang/rust/pull/46732.

**Comment by vignesh-sankaran** [comment]
What can we do to fix it? Or do we have to wait for a fix upstream?

**Comment by topecongiro** [comment]
I am currently working on it. The new version will be published within an hour.

**Comment by topecongiro** [comment]
Published 0.3.4.
